### ISSUE TITLE
Question - Is it a successor to AlpacaTag?

### ISSUE THREAD

**Issue by kuatroka** [INK-USC/LEAN-LIFE#1]
Hi. With AlpacaTag being last updated 9 months ago, can this solution be considered as its successor? I'm asking because I've tried to install the AlpacaTag. It worked for the basic labelling, butthe Active Learning Server is always off and I see you don't respond to issue raised by other people iin AlpacaTag. Therefore the question if this is the new AlpacaTag.

 Thanks

**Comment by Rahul-Khanna** [comment]
in some ways yes. in other ways no. The main thrust of this framework will be incorporating explanation capture and training of downstream models using these explanations. I'm currently working on refactoring all model training code, after doing a big refactor of the front-end code over the summer. 

@JimGong is currently working on V2 of the UI, so if you find bugs in the UI it will be swapped out soon.

Active Learning though is not a priority of this system, and not sure when we will get to that feature.

**Comment by kuatroka** [comment]
Thank you @Rahul-Khanna though I was hoping it would be. I'm on a lookout for an open source labelling/annotation tool with Active Learning to increase labelling productivity. Something like Prodigy, but free. Thanks for answering anyway!

**Comment by Rahul-Khanna** [comment]
for sure, but hopefully with this tool you won't need to label much to begin with. The goal is to use additional information (an explanation of why you labeled something the way you did) to train machines. The next release (projected 1/14/21) will allow you to train a relation extraction model with this new methodology. you can check out this paper to learn more: https://openreview.net/pdf?id=rJlUt0EYwS
